CREATE TABLE Author
(
  AuthorID INT NOT NULL,
  Name VARCHAR(50) NOT NULL,
  PRIMARY KEY (AuthorID)
);

CREATE TABLE Category
(
  CategoryID INT NOT NULL,
  CategoryName VARCHAR(50) NOT NULL,
  PRIMARY KEY (CategoryID)
);

CREATE TABLE [User]
(
  FirstName VARCHAR(50) NOT NULL,
  LastName VARCHAR(50) NOT NULL,
  UserID INT NOT NULL,
  Email VARCHAR(50) NOT NULL,
  Role VARCHAR(50) NOT NULL,
  Password VARCHAR(50) NOT NULL,
  PRIMARY KEY (UserID) 
);

CREATE TABLE Book
(
  Title VARCHAR(50) NOT NULL,
  PublicationYear INT NOT NULL,
  ISBN INT NOT NULL,
  PublisherName VARCHAR(50) NOT NULL,
  CategoryID INT,
  PRIMARY KEY (ISBN),
  FOREIGN KEY (CategoryID) REFERENCES Category(CategoryID) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE Write
(
  ISBN INT NOT NULL,
  AuthorID INT NOT NULL,
  PRIMARY KEY (ISBN, AuthorID),
  FOREIGN KEY (ISBN) REFERENCES Book(ISBN) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (AuthorID) REFERENCES Author(AuthorID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Copy
(
  Number INT NOT NULL,
  Status VARCHAR(50) NOT NULL,
  ISBN INT NOT NULL,
  PRIMARY KEY (Number, ISBN),
  FOREIGN KEY (ISBN) REFERENCES Book(ISBN) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Borrow
(
  BorrowID INT NOT NULL,
  BorrowDate DATE NOT NULL,
  ReturnDate DATE NOT NULL,
  UserID INT NOT NULL,
  Number INT NOT NULL,
  ISBN INT NOT NULL,
  UNIQUE (UserID, Number),
  PRIMARY KEY (BorrowID),
  FOREIGN KEY (UserID) REFERENCES [User](UserID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (Number, ISBN) REFERENCES Copy(Number,ISBN) ON DELETE CASCADE ON UPDATE CASCADE
);